[config]
default_to_workspace = false

[tasks."open"]
script = '''
open "https://shibuya.subscan.io/extrinsic/"
'''

[tasks."build:sol"]
script = '''
bun run build
'''

[tasks."deploy:sol"]
script = '''
bunx hardhat run deploy_sol.ts --network shibuya
'''

[tasks."build:wasm"]
script = '''
cd contracts/xvm-call
cargo contract build --release
'''

[tasks."deploy:wasm"]
script = '''
open "https://contracts-ui.substrate.io/?rpc=wss://rpc.shibuya.astar.network"
open target/ink/
'''

[tasks.'install:cargo-contract']
script = '''
# Do not run: cargo install cargo-contract, the version is v3 and old
# Run install v4
cargo install --git https://github.com/paritytech/cargo-contract --branch master cargo-contract
'''
