/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { Flipper, FlipperInterface } from "../Flipper";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool",
        name: "value",
        type: "bool",
      },
    ],
    name: "Flipped",
    type: "event",
  },
  {
    inputs: [],
    name: "data",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "flip",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060008060006101000a81548160ff02191690831515021790555061014d8061003a6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806373d4a13a1461003b578063cde4efa914610059575b600080fd5b610043610063565b60405161005091906100fc565b60405180910390f35b610061610074565b005b60008054906101000a900460ff1681565b60008054906101000a900460ff16156000806101000a81548160ff0219169083151502179055507f1865bbf6b35a0abc70661ed5e4050e07bb8d173ef7c0c116598f4d4adb7a668a60008054906101000a900460ff166040516100d791906100fc565b60405180910390a1565b60008115159050919050565b6100f6816100e1565b82525050565b600060208201905061011160008301846100ed565b9291505056fea2646970667358221220f7341f564f27953a7369c8956bb61da87e37bd5caec3d9580bc5fec20047437164736f6c63430008130033";

type FlipperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FlipperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Flipper__factory extends ContractFactory {
  constructor(...args: FlipperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Flipper & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Flipper__factory {
    return super.connect(runner) as Flipper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FlipperInterface {
    return new Interface(_abi) as FlipperInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Flipper {
    return new Contract(address, _abi, runner) as unknown as Flipper;
  }
}
