/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FlipperInterface extends Interface {
  getFunction(nameOrSignature: "data" | "flip"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Flipped"): EventFragment;

  encodeFunctionData(functionFragment: "data", values?: undefined): string;
  encodeFunctionData(functionFragment: "flip", values?: undefined): string;

  decodeFunctionResult(functionFragment: "data", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flip", data: BytesLike): Result;
}

export namespace FlippedEvent {
  export type InputTuple = [value: boolean];
  export type OutputTuple = [value: boolean];
  export interface OutputObject {
    value: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Flipper extends BaseContract {
  connect(runner?: ContractRunner | null): Flipper;
  waitForDeployment(): Promise<this>;

  interface: FlipperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  data: TypedContractMethod<[], [boolean], "view">;

  flip: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "data"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "flip"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Flipped"
  ): TypedContractEvent<
    FlippedEvent.InputTuple,
    FlippedEvent.OutputTuple,
    FlippedEvent.OutputObject
  >;

  filters: {
    "Flipped(bool)": TypedContractEvent<
      FlippedEvent.InputTuple,
      FlippedEvent.OutputTuple,
      FlippedEvent.OutputObject
    >;
    Flipped: TypedContractEvent<
      FlippedEvent.InputTuple,
      FlippedEvent.OutputTuple,
      FlippedEvent.OutputObject
    >;
  };
}
